name: CI

on:
  pull_request:
    branches: [master]
  workflow_call: # Allows this workflow to be called from other workflows

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¦ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ”§ Setup NPM and Install Dependencies
        uses: ./.github/actions/setup-npm

      - name: ğŸ§ª Run tests
        run: npm run test

      - name: ğŸ’… Check formatting
        run: npm run format:check

      - name: â›ï¸ Build the library and Storybook
        run: |
          npm run build &
          npm run build:storybook &
          wait
